name: CI/CD Hotfix

on:
  push:
    branches: [ "hotfix/*" ]

jobs:
  hotfix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./gradlew build
      - run: echo "Deploying Hotfix to Prod..."
